### PR TITLE
Change println to Log

### PR DESCRIPTION
**Pull request by wiiam**

### CODE REVIEW

**Comment by 00firestar00** [comment]
I think it would be good to set a static TAG in each class and use that. It prevents us having to write out what each one is if more Logs are added later on.

**Comment by wiiam** [comment]
Yeah I should've done that, I'll add it in later on today

**Comment by agilob** [comment]
Not sure how it works in scala, but in Java it's recommended and good practice to make them private **static final** so String object isn't created multiple times for the same class. It's faster, saves memory and prevents from "accidental" value changed.
:+1:

**Comment by wiiam** [comment]
@agilob 
val is the same as final. val = value, and var = variable
There are no static types in scala, instead an object type is used which contains static methods etc

**Comment by subliun** [comment]
I can't accept this in its current state. The definition of 'TAG' everywhere to be the same as the class name directly above it screams redundancy, especially when `this.getClass.getSimpleName` exists.

**Comment by subliun** [comment]
I don't like the ugliness that this adds to every class for little benefit. Try again using https://github.com/pocorall/scaloid/wiki/Basics#logging perhaps.

**Comment by agilob** [comment]
...

**Comment by wiiam** [comment]
>little benefit

println is uglier and isn't consistent with standard android design. Also the ability to filter the log by tag is very useful for debugging large applications when lots of information is being printed to the log at a time.

**Comment by agilob** [comment]
>Also the ability to filter the log by tag is very usef

Not only by tag but also by log level!

**Comment by subliun** [comment]
I conceed that log levels are useful, but it would be much nicer to use implicit TAGs with scaloid logging (or not use tags at all since they seem pretty useless (though I might be wrong on this point (but I doubt it))).

**Comment by subliun** [comment]
Fixed via https://github.com/subliun/Antox/commit/089542040fecc31d68a44f3ea110dbd9c4c5f4c7

**Comment by 00firestar00** [comment]
Just to chime in, I would rather have tags everywhere rather than log levels, since in most cases they are used to aid debugging, and I filter logs by tag in android studio. If all of them use "Antox" as the tag, its a bit hard to figure out where in the code that log was triggered. Maybe no one else looks at logcat while developing, but being able to filter them down to a single class file or in some cases method lets me easily see where errors or memory leaks may be occuring.

**Comment by subliun** [comment]
Yeah I see what you're saying. The new implementation (AntoxLog) allows for tags, it simply uses "Antox" as the default tag rather than forcing you to specify them everywhere. I was tossing up between the default tags method or forcing implicit tags everywhere log is used. I can easily switch to the latter if it becomes an issue.

**Comment by agilob** [comment]
The tag should be specified everywhere to allow for faster location of source of the log.

**Pull request closed without merging**
