### PR TITLE
Temporary removal of repo.tox.im repository

### PR DESCRIPTION
**Pull request by strixaluco**
As it was stated in recent blog post on https://blog.tox.chat/2015/07/current-situation-3/
"Unfortunately, Sean refuses to take responsibility for what he has done, and seems to carry the attitude that what he did was perfectly acceptable. Despite our having spent a great deal of time and effort trying to engage with him, giving him opportunities to pay us back and redeem himself (which is part of the reason why we have waited this long to make an official post about it), he has shown no remorse for his actions, and continues to hold some of our infrastructure “hostage”. This includes the tox.im, toxme.se, and libtoxcore.so domains. For this reason, we have also been forced to disassociate ourselves with the aforementioned domains and begin again from scratch with a new domain, tox.chat"

### CODE REVIEW

**Comment by lweberk** [comment]
Is there an alternative repository available to "replace" instead of removing the passage in the README?

**Comment by strixaluco** [comment]
@lweberk 
If someone is aware of trustful repo, of course it's better to replace, than to remove. But I don't know any.

**Comment by ProMcTagonist** [comment]
You can monitor the process of getting builds running again on the new domain here: https://wiki.tox.chat/infrastructure/roadmap

**Comment by strixaluco** [comment]
@ProMcTagonist 
Thank you, I've subscribed to Tox wiki to monitor it. However, I still suppose that to temporarily remove link to non-trustful repo is lesser evil, than to keep it for usage.

**Comment by lweberk** [comment]
@strixaluco 
You're right. I have to agree with that.

**Comment by subliun** [comment]
fixed via - https://github.com/subliun/Antox/commit/2e33675b6d086adeb35f84461d93bfdf41fe6e5a

**Pull request closed without merging**
