### PR TITLE
tox.im is history

### PR DESCRIPTION
**Pull request by ameenross**
Remove tox.im F-Droid repo from README

### CODE REVIEW

**Comment by subliun** [comment]
I'm waiting for an alternative F-Droid repo to be set up before removing the current one.

**Comment by ameenross** [comment]
Is the current one receiving updates though? I can't even seem to connect, really.

**Comment by hexphase** [comment]
Yeah looks like the current repo in the readme is dead. An alternative f-droid repo has been setup. Please update the repo to..

https://antox.me/fdroid/repo

**Comment by cebe** [comment]
that website shows a HTTP 403 error.

**Comment by hexphase** [comment]
The guys on freenode #tox pointed me toward that repo, which I just tested out myself and got a working antox install after adding it to my repo list.

Yes, visiting the site via web browser produces a 403.

**Comment by ameenross** [comment]
So is the repo at antox.im ready for inclusion in the Readme?

**Comment by hexphase** [comment]
Just tested it again. All looks good!

**Pull request closed without merging**
