### PR TITLE
Use RecyclerView for ChatActivity, fix issues around file transfers and image loading

### PR DESCRIPTION
**Pull request by 00firestar00**
Normally I try to not do large pull requests, but if you break it down there wasn't a lot that was actually altered. Most of the code in the original adapter was just moved to viewholders. I was hoping that this would help flush out the memory leak around loading images too many times from cache, but I'll have to save that for another time.
I tried keeping the same code style used in the rest of the app, but i'm not really use to this style nor scala so let me know is anything needs to be formatted differently

Some of the major fixes:
 * removed 'com.github.machinarius:preferencefragment:0.1.1' dependency as it is no longer used
 * swapped out ListView for RecyclerView, fixed formatting on activity_chat.xml
 * deleted chat_message_row.xml and instead broke it up into individual xml views for the various message types. helps prevent having to toggle the visibility on every single element (FileMessages could still use some work)
 * created viewholders for the message types and moved a lot of the functionality from the adapter to those viewholders.
 * fixed click on longClick actions on all messages
 * added option to delete file along with the file/image message
 * set maxHeight  and maxWidth on images

### CODE REVIEW

**Comment by subliun** [comment]
Hey. This looks good for the most part. I've been meaning to split up the message adapter for a long time, thanks for doing it. :) 

However, I've run into some problems where unsent messages/file transfers are remaining transparent even after they've been sent. Also once I managed to get ghost messages to hover above other messages (can't reproduce at the moment, so don't worry too much). You should probably change the camelCaseXml ids in activity_chat.xml into snake_case to fit better with the rest of the project since you cleaned up the rest of that file. 

>It would be better to use Ints instead of Enums for MessageType
I don't believe the hype about enums being terribly inefficient, and I prefer the type safety you get with enums, but I don't really mind that you've used them for TEXT, ACTION, FILE here either. 

Everything else seems to be working correctly.

**Comment by 00firestar00** [comment]
I've seen the transparent message bug, never seen them overlap other messages though. Prior to migrating the code I never saw transparent messages so  I guessed I kind of fixed it. Will look into that though.

Enums themselves are not that bad, and I don't know if scala made any improvements to them. The problem is people tend to overdo it and use them all over the place when a few static integers would do just fine. As for the type safety, I agree with you on that, which is why I use the `@IntDef` android support annotations in my personal projects http://tools.android.com/tech-docs/support-annotations
Android API methods tend to use integers to represent types, so Enums can get to be a little hard to work with. Its not too bad the way I have it in the adapter right now, and I wouldn't want to completely rework how the MessageTypes work, just something I would recommend.

Let me know if you find anything else, and I'll be able to get a fix in the next day or so

**Comment by 00firestar00** [comment]
Those 2 commits should take care of the 2 things you pointed out

**Comment by subliun** [comment]
The animations are causing the ghosting issue. Try scrolling while receiving messages. I'll try to work on a fix.

**Comment by subliun** [comment]
merged with animations removed

**Comment by 00firestar00** [comment]
I had to really spam myself with messages while scrolling to get it to glitch out. 

I think the way to do the animations would require the adapter to use "notifyItemInserted" to trigger an animation, but then the message observer would have to change to only add new messages instead of removing and readding all

**Comment by subliun** [comment]
Yeah. That would be the best way to do it, and I tried to make notifyItemInserted trigger the animations correctly. I didn't manage to get it working though.

**Pull request closed without merging**
