### PR TITLE
Improved Notifications

### PR DESCRIPTION
**Pull request by wiiam**
- Added persistent notification
- Added options for vibrate/sound/light
- Show avatar in notification
- Fixed an issue where unread counts could not be read (caused by https://github.com/subliun/Antox/commit/f795b3b096a58199e126f44562d303db90c3668e)
- Move the unread count to contentinfo
- Fixed an issue where all unread counts were being cleared when a chat activity is opened (instead of just the unread counts for that friend)

Update: removed timestamp on persistent notification

### CODE REVIEW

**Comment by agilob** [comment]
<3

**Comment by subliun** [comment]
Format your code. There is inconsistent formatting throughout.

https://github.com/subliun/Antox/pull/183/files#diff-f8effd5241f1f432f81a97a422ab4860R133
https://github.com/subliun/Antox/pull/183/files#diff-f8effd5241f1f432f81a97a422ab4860R141
'on' is a bad variable name

https://github.com/subliun/Antox/pull/183/files#diff-16360210d75cf6ae88a2e28d36c29bdaR61
use antoxlog

https://github.com/subliun/Antox/pull/183/files#diff-9af39348b8eaf8757d5e88a414d156abR21
poor spacing

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R25
https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R26
null should be replaced with an Option

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R27
rename to 'persistentNotificationEnabled'

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R147
this is copy pasted below

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R168
rename to 'notification'

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R146
toxsingleton.tox shouldn't be null
either way that if is weird
you've got the same code in the else if

https://github.com/subliun/Antox/pull/183/files#diff-ab3106adc953305ff89bd4a1d0b7f3ffR21
no committing commented code

https://github.com/subliun/Antox/pull/183/files#diff-437b1da59163a6f60ef55e0a53fe2db9R70
should be in strings.xml


P.S. I should really just make comments on the code next time huh.

**Comment by agilob** [comment]
<3

**Comment by dcharles525** [comment]
<3

**Pull request merged**
